dist: trusty
sudo: required

language: go

go:
- "1.10"
- "1.11"

before_script:
- go get github.com/valyala/fastrand
- go get github.com/mattn/goveralls

script: go test -v ./... && $HOME/gopath/bin/goveralls -service=travis-ci