dist: trusty
sudo: required

language: go

go:
  - "1.12"
  - "1.13"

before_script:
  - go get -u github.com/mattn/goveralls

script: GO111MODULE=on go test -v ./... && $HOME/gopath/bin/goveralls -service=travis-ci
